### ISSUE TITLE
Project still alive

### ISSUE THREAD

**Issue by LukasK13** [bob1de/hass-apps#66]
Hello @bob1de ,

Thank you for your amazing work. I was wondering if hass-apps and schedy is still alive, since there hasn't been a commit for more than a year.

Thanks.

**Comment by bob1de** [comment]
Hi,

Well, I mainly wrote Schedy to suit my own demands, and since it lacks nothing I personally need, it stays as it is right now.

Of course I try to fix critical bugs, but for now you can assume it to be in a kind of maintenance only mode.

Best regards
Robert

**Comment by LukasK13** [comment]
Thank you Robert for your answer. I would recommend you to mention the maintenance only mode in the readme such that new users know what they are up to.
Again thanks for your great work.

**Comment by bob1de** [comment]
Thanks for the suggestion, done.
